### ISSUE TITLE
Error thrown whenever there is a visit

### ISSUE THREAD

**Issue by adaliszk** [SteffTek/swf-dev-kit#2]
I am running the plugin on a waterfall server (build 341, commit a469ee5), every time when there is a visitor the console yields a cast error.

The site loads just fine, I imagine that somewhere there is a need for type checks :) I would have been opened a pull request already if the source would have been open.

Console output:
```
> 05:55:01 [SEVERE] java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonArray
> 05:55:01 [SEVERE] at S$SSSS$$$SSS$$$$$S$SS$$$$$SSS$SSSSS$SS$$$S$SS$$S$S$SS$SSSS$$SSSS$$$$SSSSS$SS$S$$$$$$$SS$S$$$$S$$SSS$$S$$S$$$$S$SS$SSSS$SS$S$$SS$$S$$$SSS$SSSSSSS$S$S$$$S$$S$$SSSS$S$SS$$SSSSSSSSSS$SSS$S$S$S$S$$SSSSSS$$$SS$S$S$$$$SSS$$$$SSS$$$$$SSSSSSS$$SS$$$SSSSS$$SSS$$SSSS$SS$$SSSS$SS$SS$$$$$$SS$SS$SSS$S$$SS$SS$SS$SSS$$SSSS$$$$S$$$S$S$$S$S$$S$$$SS$$S$SSS$SS$$SSSS$$$$S$SS$$SSS$$SSS$SS.$SSSS$SS$$SSSSS$$$$$$SSSSSSSS$$SS$$SS$SSSS$$$S$$SS$S$$$SSSS$S$S$SSS$$$$$$S$$SSS$$$SS$$S$S$S$$SS$SS$S$S$$SSS$SS$SS$SSS$S$$$S$S$$$$$$$SSS$S$$S$S$$$$S$$$S$S$S$$S$S$S$$$SSS$$SS$$SS$$S$S$SSS$$$$S$SSSS$$$$$$$SS$$$$S$S$SS$S$$$$$S$S$S$$S$SS$$$$$$$SSSS$SSS$S$$SS$$$$S$S$SSS$$SS$S$$SSS$$$S$SS$$$$$SSSSSSS$S$$SSS$$$SS$SSSSS$$$SSSSS$$SSS$S$SSS$$SSS$$S$$SSSSS$S$SS$SS$SS$SSS$$$$$S$$(Unknown Source)
> 05:55:01 [SEVERE] at $SS$$$SSSS$$S$S$$SSSS$$$S$S$SS$$$S$$S$$S$SSS$$$SSS$$SS$$S$$S$S$SS$$S$SSSS$S$$$$$$S$$SS$SSS$$$SS$$$SSSS$SSSSS$$SSSSSSS$S$SS$SSSS$$$$S$SS$$$S$S$$$$SS$SS$$$S$S$$$SS$$$S$SSS$$$SSS$$$SS$S$$SSS$$SS$$S$$$$SS$$$$$S$$$S$SS$$$$SS$S$S$$$SSS$$$SSSSSS$SSSSSSS$$SSS$$$$$$$S$SSSSSSS$SSSS$$SS$SSS$SSS$$$SS$$SS$$SSSS$SSS$SS$$$$S$SS$$$S$$$$S$S$SS$S$$$S$SSS$S$S$$S$$$S$$SSS$$$$SS$SS$$$SSS.$SSSS$SS$$SSSSS$$$$$$SSSSSSSS$$SS$$SS$SSSS$$$S$$SS$S$$$SSSS$S$S$SSS$$$$$$S$$SSS$$$SS$$S$S$S$$SS$SS$S$S$$SSS$SS$SS$SSS$S$$$S$S$$$$$$$SSS$S$$S$S$$$$S$$$S$S$S$$S$S$S$$$SSS$$SS$$SS$$S$S$SSS$$$$S$SSSS$$$$$$$SS$$$$S$S$SS$S$$$$$S$S$S$$S$SS$$$$$$$SSSS$SSS$S$$SS$$$$S$S$SSS$$SS$S$$SSS$$$S$SS$$$$$SSSSSSS$S$$SSS$$$SS$SSSSS$$$SSSSS$$SSS$S$SSS$$SSS$$S$$SSSSS$S$SS$SS$SS$SSS$$$$$S$$(Unknown Source)
> 05:55:01 [SEVERE] at SS$$S$$$SS$SSSS$S$$$S$$S$$$$$$$SS$$$$$$$SSS$$SSS$$S$$S$S$$$S$$S$$S$S$$$$S$SS$$$S$S$$$$$$$SSSSSSSS$$S$SS$S$$S$$SS$$$SS$$$$$$SS$$$$S$$$S$$SS$SS$$SSS$SS$$$$S$$S$$SSS$S$S$S$$$$SS$SS$S$$$S$SS$$S$SSSSSS$S$S$$$$SSS$$SSS$S$S$S$S$S$$S$$$SSSS$$SS$S$S$SSSS$$$$$$SS$S$S$SSS$$S$$$$$SSS$SS$$$SSSS$$SS$$$$$SSSSS$$$$$$SS$$SSSS$S$$SS$SS$S$$$$$SSSSS$$SS$SSS$S$$$$S$$$S$$SS$$$$$SS$$SSS$$$.SSS$$$SSSS$$$$$S$S$$$$$SSS$$S$S$SSSS$S$$$$$SSS$$SS$SSSS$$SS$$$S$$S$S$SS$SSSSSS$SS$$SS$SSSS$$SSSSSSSSS$S$SS$S$$SS$S$SS$SSS$S$SS$$SSSS$SS$$$$$$SSSS$$$SSSS$$S$SS$S$$$$SS$$$S$$SS$SS$S$S$S$$SS$$SS$S$$$$SSS$$SSS$SS$$$$S$SS$$$SS$S$SSS$$$$SS$SS$SS$$SSSSSS$S$S$SS$S$S$S$SS$S$S$SS$$$S$SS$$$$$$$SSS$$$SSS$$S$$S$$$S$$$$SS$$$$$$S$S$$$$$SS$$$SS$SSS$SSSSS$$$$SSS$SSS$$SS$$$$$$$SSSSSS$(Unknown Source)
> 05:55:01 [SEVERE] at SS$$S$$$SS$SSSS$S$$$S$$S$$$$$$$SS$$$$$$$SSS$$SSS$$S$$S$S$$$S$$S$$S$S$$$$S$SS$$$S$S$$$$$$$SSSSSSSS$$S$SS$S$$S$$SS$$$SS$$$$$$SS$$$$S$$$S$$SS$SS$$SSS$SS$$$$S$$S$$SSS$S$S$S$$$$SS$SS$S$$$S$SS$$S$SSSSSS$S$S$$$$SSS$$SSS$S$S$S$S$S$$S$$$SSSS$$SS$S$S$SSSS$$$$$$SS$S$S$SSS$$S$$$$$SSS$SS$$$SSSS$$SS$$$$$SSSSS$$$$$$SS$$SSSS$S$$SS$SS$S$$$$$SSSSS$$SS$SSS$S$$$$S$$$S$$SS$$$$$SS$$SSS$$$.channelRead0(Unknown Source)
> 05:55:01 [SEVERE] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
> 05:55:01 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> 05:55:01 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> 05:55:01 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 05:55:01 [SEVERE] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 05:55:01 [SEVERE] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 05:55:01 [SEVERE] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 05:55:01 [SEVERE] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 05:55:01 [SEVERE] at java.lang.Thread.run(Thread.java:748)
> 05:55:01 [SEVERE] java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonArray
> 05:55:01 [SEVERE] at SSSSS$$$$$SS$SSSSSSSSSS$$SS$$SS$$SS$$$$SSSSS$$SS$SSS$S$S$S$$$$SSS$SSSS$$$S$SS$$S$$$S$$SS$S$$SS$$$SS$$S$SS$$$S$SSSSSSSSS$$S$S$$S$S$$$$S$$$S$$$SSS$$$$$S$$S$$SS$S$$$SSS$SSSSSS$SSS$S$SSSSS$S$S$$$$SSS$SSS$$S$$S$$SS$S$SS$SS$SS$$S$S$S$SSSSS$$SS$$SSSSSSS$SSS$SSS$SS$S$$$SSSS$$$S$S$S$S$S$$SSSS$SS$SSSSSSSS$S$SS$S$$SSSSS$$SSS$SS$$$S$S$SSSS$$$SSS$$$SSSSS$S$$$$$$S$$SS$$$$$SS$S$$S$.$SSSS$SS$$SSSSS$$$$$$SSSSSSSS$$SS$$SS$SSSS$$$S$$SS$S$$$SSSS$S$S$SSS$$$$$$S$$SSS$$$SS$$S$S$S$$SS$SS$S$S$$SSS$SS$SS$SSS$S$$$S$S$$$$$$$SSS$S$$S$S$$$$S$$$S$S$S$$S$S$S$$$SSS$$SS$$SS$$S$S$SSS$$$$S$SSSS$$$$$$$SS$$$$S$S$SS$S$$$$$S$S$S$$S$SS$$$$$$$SSSS$SSS$S$$SS$$$$S$S$SSS$$SS$S$$SSS$$$S$SS$$$$$SSSSSSS$S$$SSS$$$SS$SSSSS$$$SSSSS$$SSS$S$SSS$$SSS$$S$$SSSSS$S$SS$SS$SS$SSS$$$$$S$$(Unknown Source)
> 05:55:01 [SEVERE] at $SS$$$SSSS$$S$S$$SSSS$$$S$S$SS$$$S$$S$$S$SSS$$$SSS$$SS$$S$$S$S$SS$$S$SSSS$S$$$$$$S$$SS$SSS$$$SS$$$SSSS$SSSSS$$SSSSSSS$S$SS$SSSS$$$$S$SS$$$S$S$$$$SS$SS$$$S$S$$$SS$$$S$SSS$$$SSS$$$SS$S$$SSS$$SS$$S$$$$SS$$$$$S$$$S$SS$$$$SS$S$S$$$SSS$$$SSSSSS$SSSSSSS$$SSS$$$$$$$S$SSSSSSS$SSSS$$SS$SSS$SSS$$$SS$$SS$$SSSS$SSS$SS$$$$S$SS$$$S$$$$S$S$SS$S$$$S$SSS$S$S$$S$$$S$$SSS$$$$SS$SS$$$SSS.$SSSS$SS$$SSSSS$$$$$$SSSSSSSS$$SS$$SS$SSSS$$$S$$SS$S$$$SSSS$S$S$SSS$$$$$$S$$SSS$$$SS$$S$S$S$$SS$SS$S$S$$SSS$SS$SS$SSS$S$$$S$S$$$$$$$SSS$S$$S$S$$$$S$$$S$S$S$$S$S$S$$$SSS$$SS$$SS$$S$S$SSS$$$$S$SSSS$$$$$$$SS$$$$S$S$SS$S$$$$$S$S$S$$S$SS$$$$$$$SSSS$SSS$S$$SS$$$$S$S$SSS$$SS$S$$SSS$$$S$SS$$$$$SSSSSSS$S$$SSS$$$SS$SSSSS$$$SSSSS$$SSS$S$SSS$$SSS$$S$$SSSSS$S$SS$SS$SS$SSS$$$$$S$$(Unknown Source)
> 05:55:01 [SEVERE] at SS$$S$$$SS$SSSS$S$$$S$$S$$$$$$$SS$$$$$$$SSS$$SSS$$S$$S$S$$$S$$S$$S$S$$$$S$SS$$$S$S$$$$$$$SSSSSSSS$$S$SS$S$$S$$SS$$$SS$$$$$$SS$$$$S$$$S$$SS$SS$$SSS$SS$$$$S$$S$$SSS$S$S$S$$$$SS$SS$S$$$S$SS$$S$SSSSSS$S$S$$$$SSS$$SSS$S$S$S$S$S$$S$$$SSSS$$SS$S$S$SSSS$$$$$$SS$S$S$SSS$$S$$$$$SSS$SS$$$SSSS$$SS$$$$$SSSSS$$$$$$SS$$SSSS$S$$SS$SS$S$$$$$SSSSS$$SS$SSS$S$$$$S$$$S$$SS$$$$$SS$$SSS$$$.SSS$$$SSSS$$$$$S$S$$$$$SSS$$S$S$SSSS$S$$$$$SSS$$SS$SSSS$$SS$$$S$$S$S$SS$SSSSSS$SS$$SS$SSSS$$SSSSSSSSS$S$SS$S$$SS$S$SS$SSS$S$SS$$SSSS$SS$$$$$$SSSS$$$SSSS$$S$SS$S$$$$SS$$$S$$SS$SS$S$S$S$$SS$$SS$S$$$$SSS$$SSS$SS$$$$S$SS$$$SS$S$SSS$$$$SS$SS$SS$$SSSSSS$S$S$SS$S$S$S$SS$S$S$SS$$$S$SS$$$$$$$SSS$$$SSS$$S$$S$$$S$$$$SS$$$$$$S$S$$$$$SS$$$SS$SSS$SSSSS$$$$SSS$SSS$$SS$$$$$$$SSSSSS$(Unknown Source)
> 05:55:01 [SEVERE] at SS$$S$$$SS$SSSS$S$$$S$$S$$$$$$$SS$$$$$$$SSS$$SSS$$S$$S$S$$$S$$S$$S$S$$$$S$SS$$$S$S$$$$$$$SSSSSSSS$$S$SS$S$$S$$SS$$$SS$$$$$$SS$$$$S$$$S$$SS$SS$$SSS$SS$$$$S$$S$$SSS$S$S$S$$$$SS$SS$S$$$S$SS$$S$SSSSSS$S$S$$$$SSS$$SSS$S$S$S$S$S$$S$$$SSSS$$SS$S$S$SSSS$$$$$$SS$S$S$SSS$$S$$$$$SSS$SS$$$SSSS$$SS$$$$$SSSSS$$$$$$SS$$SSSS$S$$SS$SS$S$$$$$SSSSS$$SS$SSS$S$$$$S$$$S$$SS$$$$$SS$$SSS$$$.channelRead0(Unknown Source)
> 05:55:01 [SEVERE] at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
> 05:55:01 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> 05:55:01 [SEVERE] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> 05:55:01 [SEVERE] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 05:55:01 [SEVERE] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 05:55:01 [SEVERE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 05:55:01 [SEVERE] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 05:55:01 [SEVERE] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 05:55:01 [SEVERE] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 05:55:01 [SEVERE] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 05:55:01 [SEVERE] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 05:55:01 [SEVERE] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 05:55:01 [SEVERE] at java.lang.Thread.run(Thread.java:748)
```

**Comment by SteffTek** [comment]
Can you please attach your Configs/WebBuilder Files? Maybe your custom template.

Since I didnt continue this project for a while, I might open it to the public.

**Comment by adaliszk** [comment]
Hey, sorry for the late response. I packed up the whole plugin folder for you :)

[SpigotWebFramework.zip](https://github.com/SteffTek/swf-dev-kit/files/4592961/SpigotWebFramework.zip)

**Comment by SteffTek** [comment]
Ok I sovled your problem. Your Footer and Navbar files are empty. There need to be at least an Empty JsonArray (literally "[]") inside the file. I'll work on a fix. For now, if you don't want to use the Navbar nor the Footer, just type `[]`.

**Comment by adaliszk** [comment]
Thank you!

**Comment by SteffTek** [comment]
I uploaded the new version. And it's unobfuscated now. I won't make it open source by now but it should help understanding error messages (for you and for me)

**Comment by adaliszk** [comment]
Nice, thank you!
That should help quite a lot for debugging :)
